services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '54321:5432'
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - distributed-atm-net

  distributedATM:
    image: 'nycolaskcn/distributed-atm'
    depends_on:
      - db
    ports:
      - '8080:8080'
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - distributed-atm-net

networks:
  distributed-atm-net:
    driver: bridge

volumes:
  db-data:
