spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: sistemaBancario
  profiles:
    active: ${APP_PROFILE}
security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration: 3600000