spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${HOST_DB}:${PORT_DB}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: error